In [6]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

a = np.array([1,2,3,4])
print(a)
print(type(a))

a = np.arange(10)
print(a)

l = range(100)
a = np.arange(100)

a = np.array([1,2,3,4])
print(a.ndim)

b = np.array([[1,2,3],[4,5,6]])
print(b.ndim)
print(b)

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.ndim)

print(a.shape)
print(b.shape)
print(c.shape)

a = np.arange(1,10,2)
print(a)

a = np.linspace(0,1,6)
print(a)

a = np.ones((3,3))
print(a)

a = np.zeros((3,3))
print(a)

a = np.eye(3)
print(a)

a = np.eye(3,2)
print(a)

a = np.diag([1,2,3,4])
print(a)
print(np.diag(a))

a = np.arange(10,dtype="float")
print(a.dtype)

a = np.array([1+2j,2+4j])
print(a.dtype)

a = np.array([True,False])
print(a.dtype)

a = np.arange(10)
print(a[5])

a = np.diag([1,2,3])
print(a[2,2])

a = np.arange(10)
print(a[1:8:2])

a = np.arange(10)
b = a[::2]
print(np.shares_memory(a,b))

b = a[::2].copy()
print(np.shares_memory(a,b))

a = np.random.randint(0,20,15)
mask = (a%2==0)
a[mask] = -1
print(a)

a = np.array([1,2,3,4])
print(a+1)
print(a**2)

b = np.ones(4)+1
print(a*b)

c = np.diag([1,2,3,4])
print(c.dot(c))

a = np.array([1,2,3,4])
b = np.array([5,2,7,4])
print(a==b)
print(np.array_equal(a,b))

a = np.array([1,0,1,0],dtype="bool")
b = np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))

a = np.arange(5)
print(np.sin(a))
print(np.exp(a))

x = np.array([[1,2],[1,2]])
print(x.sum(axis=0))

import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\narasimha\Downloads\weather_dataset.csv")

print("Original Data")
print(df)

print("Missing Values")
print(df.isnull().sum())

df["temperature_c"] = df["temperature_c"].fillna(df["temperature_c"].mean())
df["humidity_percent"] = df["humidity_percent"].fillna(df["humidity_percent"].mean())
df["rain_mm"] = df["rain_mm"].fillna(df["rain_mm"].mean())
df["wind_kmph"] = df["wind_kmph"].fillna(df["wind_kmph"].mean())

print("After Filling Missing Values")
print(df)

print("Missing Values After Cleaning")
print(df.isnull().sum())

print("Maximum Temperature:", df["temperature_c"].max())
print("Minimum Temperature:", df["temperature_c"].min())
print("Average Temperature:", df["temperature_c"].mean())

print("Maximum Rainfall:", df["rain_mm"].max())
print("Average Wind Speed:", df["wind_kmph"].mean())

print("Summary Statistics")
print(df.describe())

[1 2 3 4]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
1
2
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(4,)
(2, 3)
(2, 2, 2)
[1 3 5 7 9]
[0.  0.2 0.4 0.6 0.8 1. ]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]
float64
complex128
bool
5
3
[1 3 5 7]
True
False
[ 7 11 15 13 17 19  9 -1 15  3 11 -1  9 -1  9]
[2 3 4 5]
[ 1  4  9 16]
[2. 4. 6. 8.]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[False  True False  True]
False
[ True  True  True False]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[2 4]
Original Data
    Unnamed: 0.1        date  temperature_c  humidity_percent  rain_mm  \
0              0  01-01-2024           20.0                60        5   
1              1  02-01-2024           20.3                62        0   
2         